// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr70407lIS3zHXGBU4ql5Rs3c1YG4b65A',
    appId: '1:79604815900:web:20392c59b2497032fb27d9',
    messagingSenderId: '79604815900',
    projectId: 'smart-meal-planner-51d03',
    authDomain: 'smart-meal-planner-51d03.firebaseapp.com',
    storageBucket: 'smart-meal-planner-51d03.firebasestorage.app',
    measurementId: 'G-477C3CH0RW',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr70407lIS3zHXGBU4ql5Rs3c1YG4b65A',
    appId: '1:79604815900:web:576a6faee63bf248fb27d9',
    messagingSenderId: '79604815900',
    projectId: 'smart-meal-planner-51d03',
    authDomain: 'smart-meal-planner-51d03.firebaseapp.com',
    storageBucket: 'smart-meal-planner-51d03.firebasestorage.app',
    measurementId: 'G-GZJRPLL22V',
  );
}
